services:
  app:
    build: ./app
    container_name: networking-app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/testdb
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    container_name: networking-mongo
    ports:
      - "27017:27017"
